PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#> 
PREFIX nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> 
PREFIX powla: <http://purl.org/powla/powla.owl#> 
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX terms: <http://purl.org/acoli/open-ie/> 
PREFIX x:     <http://purl.org/acoli/conll-rdf/xml#> 
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>

######################
# serialize sentence #
######################

INSERT { ?s conll:SENTENCE ?text }
WHERE { 
	?s a nif:Sentence.
	{ SELECT ?s (GROUP_CONCAT(?word; separator=" ") as ?text)
	  WHERE {
	  	?w a nif:Word.
		MINUS { [] nif:nextWord ?w }
		?w conll:HEAD+ ?s.
		?s a nif:Sentence.
		?w nif:nextWord*/conll:FORM ?word.
	  } GROUP BY ?s
	} 
};

