PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#> 
PREFIX nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> 
PREFIX powla: <http://purl.org/powla/powla.owl#> 
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX terms: <http://purl.org/acoli/open-ie/> 
PREFIX x:     <http://purl.org/acoli/conll-rdf/xml#> 
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>

SELECT ?sid ?nid ?discourse_marker ?pred ?text ?suri
WHERE {
	?s a nif:Sentence.
	BIND(str(?s) as ?suri)
	BIND(strbefore(strafter(?suri,"#s") ,"_") as ?sid)
	OPTIONAL { ?s conll:DISCOURSE_MARKER ?discourse_marker }
	?s conll:NUC/conll:ID ?nid.
	?s conll:PRED ?pred.
	?s conll:SENTENCE ?text.
} LIMIT 1