PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#> 
PREFIX nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> 
PREFIX powla: <http://purl.org/powla/powla.owl#> 
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX terms: <http://purl.org/acoli/open-ie/> 
PREFIX x:     <http://purl.org/acoli/conll-rdf/xml#> 
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>

# produces nif:Sentence a with conll:DISCOURSE_MARKER

# this implementation is much more heuristic than the one in discourse2.sparql
# so, it will massively overgenerate
# at the same time, it is also more robust against parser errors and capable of retrieving multi-word discourse markers

##################################################
# retrieve phrases from sentence with depth <= 3 #
##################################################

INSERT { ?s conll:PHRASE ?phrase }
WHERE {
	{ SELECT ?s (GROUP_CONCAT(?word; separator=" ") as ?phrase)
		WHERE {
			?s a nif:Sentence.
			?first conll:HEAD+ ?s.
			MINUS { [] nif:nextWord ?first }. 			
			?first nif:nextWord* ?tmp.
			?tmp (((conll:HEAD)?/conll:HEAD)?/conll:HEAD) ?s.
			?tmp conll:FORM ?word.
		} GROUP BY ?s
	}
};

##########################
# find discourse markers #
##########################
# check whether the PHRASE contains a discourse marker

# identify discourse marker candidates (using the conll:PHRASE nodes established above)
# (from DimLex)
INSERT { ?s conll:DISCOURSE_MARKER ?mlemma }
WHERE { ?s conll:PHRASE ?phrase .
	GRAPH <http://purl.org/acoli/dimlex> {
		[] ontolex:writtenRep ?orig.
		BIND(concat(" ",lcase(str(?orig))," ") as ?wrep)
	}
	FILTER(contains(concat(" ",lcase(?phrase)," "),?wrep))
	bind(str(?orig) as ?mlemma)
};

# keep the longer discourse marker
DELETE { ?marker conll:DISCOURSE_MARKER ?short }
WHERE { ?marker conll:DISCOURSE_MARKER ?short, ?long
	FILTER(strlen(?long)>strlen(?short))
};

# keep the alphabetically first discourse marker
DELETE { ?marker conll:DISCOURSE_MARKER ?second }
WHERE { ?marker conll:DISCOURSE_MARKER ?first, ?second
	FILTER(?first > ?second)
};

#######################
# add a question mark #
#######################
# to verify automatically identified discourse markers

DELETE { ?s conll:DISCOURSE_MARKER ?old }
INSERT { ?s conll:DISCOURSE_MARKER ?new }
WHERE { ?s conll:DISCOURSE_MARKER ?old. BIND(concat(?old,"?") as ?new) };