PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#> 
PREFIX nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> 
PREFIX powla: <http://purl.org/powla/powla.owl#> 
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX terms: <http://purl.org/acoli/open-ie/> 
PREFIX x:     <http://purl.org/acoli/conll-rdf/xml#> 

# # noch nicht voll eingearbeitet
# ? zero: pro-drop
# 	- subjekt kann stilistisch sein
# ! klitische pronomina
# 	verdere => vederlo "ihn sehen"
# ? pers pron
# 	lemma="io|tu"
# 	lemma="lui|lei", arch "egli|ella" (nur stilistisch), "esso|essa" (nur stilistisch)
# 	lemma="noi" 1pl., "voi"
# 	lemma="loro", arch. "essi" m.pl., "esse" f.pl.
# 	objektpronomen "mi", kann reflexiv (aka "expl") sein
# reflexivpronomen
# 	"mi", "ti"; "ci", "vi" = objektpronomen
# 	"si" (sg. und pl.) != onjektpronomen
# poss.pron?
# 	- lemma="loro" auch poss.pron., sonst nicht
# 	- liste extrahieren
# 		[feats = ".*Poss=Yes.*"] :: match.text_lang = "Italian" within text 
# dem (prox/dist)
# 	- "diese", questo, questa, questi, queste
# 	- "jene", quello (steht alleine), quella, quel, quell', quelli, quelle
# 	- stilistisch höher: codesto, codesta, codesti, codeste
# dem NP
# 	- dieselben formen
# 	- steht immer initial
# ? relativpronomen anders
# indef. NP
# 	- "un", "una", "uno", "un'" [f.] oblig.
# 	- vor der NP
# def. NP
# 	- "la", "lo", "il", "le", "gli", "i"
# 	- vor der NP
# "la casa mia"
# 	- emph., nicht standard, ggf. regional

###########################
# eliminate non-markables #
###########################

# non-markables (REF=_)
INSERT { ?w conll:REF "_" } 
WHERE { 
	# Reflexive pronouns (English *herself*, etc.) are not PM.
	{ ?w conll:FEATS ?f FILTER(contains(?f,"Reflex=Yes")) } UNION
	# expletives
	{ ?w conll:EDGE "expl" } UNION
	# dependent nouns
	{ ?w conll:EDGE "flat"} UNION
	{ ?w conll:EDGE "compound"} UNION
	# relatve pronouns
	{ ?w conll:EDGE "mark"} UNION
	{ ?w conll:UPOS "SCONJ" } UNION
	{ ?w conll:FEATS ?f FILTER(contains(?f,"PronType=Rel"))} UNION
	# non-nominals
	{ ?w conll:EDGE "amod"} UNION
	{ ?w conll:EDGE "advmod"} 
};

#################################
# REF_EXP (NP_TYPE) annotations #
#################################

# REF_EXP
# - indefinite and interrogative pronouns => ?NEW
# - NOT IDENTIFIED: NP with indefinite "semi-demonstrative" (English "such") => ?NEW
# - NAME proper names => ?OLD ("primary markable")
# - DEF_NP definite NP => ?OLD
# - DEM_NP demonstrative NP => ?OLD
# - POSS_NP possessive NP => ?NEW
# - INDEF_NP indefinite NP => ?NEW (secondary markable)
# - PPER personal pronouns => ?OLD
# - PPOSS possessive pronouns => ?OLD
# - PDEM substitutive demonstrative pronouns => ?OLD
# - PADV pronominal adverbs => ?OLD
# - PIND indefinite pronoun => ?NEW (secondary markable)

# Note: to facilitate navigation during spreadsheet-based annotation, we remove `?NEW` in a final processing step.

# - interrogative pronouns => ?NEW
INSERT {
	?w conll:REF "?NEW"; conll:REF_EXP "pron.pint"
} WHERE {
	?w conll:FEATS ?f FILTER(contains(?f,"PronType=Int"))
	MINUS { ?w conll:REF [] }
};

# - relative pronouns => BOUND
INSERT {
	?w conll:REF "BOUND".
} WHERE {
	?w conll:FEATS ?f FILTER(contains(?f,"PronType=Rel"))
	MINUS { ?w conll:REF [] }
};



## - NP with indefinite "semi-demonstrative" (English "such") => ?NEW
#INSERT {
#	?w conll:REF "?NEW"; conll:REF_EXP "pron.pds"
#} WHERE {
#	?dep conll:LEMMA "such"; conll:EDGE ?e; conll:HEAD ?w.
#	FILTER(strstarts(?e,"det") || strstarts(?e,"amod"))
#	MINUS { ?w conll:REF [] }
#};

# - PPOSS possessive pronouns => ?OLD
INSERT {
	?w conll:REF_EXP "pron.ppos"; conll:REF "?OLD"
} WHERE {
	?w conll:UPOS "DET"; conll:FEATS ?f.
	FILTER(contains(?f,"PronType=Prs"))
	MINUS { ?w conll:REF [] }
};

# - PDEM substitutive demonstrative pronouns => ?OLD
INSERT {
	?w conll:REF_EXP "pron.pds"; conll:REF "?OLD"
} WHERE {
	?w conll:UPOS "PRON"; conll:FEATS ?f.
	FILTER(contains(?f,"PronType=Dem"))
	MINUS { ?w conll:REF [] }
};

# - PADV pronominal adverbs => ?OLD, REF_EXP = pron.padv
# not sure this exists in Italian as a morphosyntactic category

# - PIND indefinite pronoun => ?NEW (secondary markable)
INSERT {
	?w conll:REF "?NEW"; conll:REF_EXP "pron.pind"
} WHERE {
	?w conll:UPOS "PRON"; conll:FEATS ?f.
	FILTER(contains(?f,"PronType=Ind"))
	MINUS { ?w conll:REF [] }
};

# - PPER personal pronouns => ?OLD
INSERT {
	?w conll:REF_EXP "pron.pper"; conll:REF "?OLD"
} WHERE {
	?w conll:UPOS "PRON"; conll:FEATS ?f.
	FILTER(contains(?f,"PronType=Prs"))
	MINUS { ?w conll:REF [] }
};

# - other pronouns => ?OLD
INSERT {
	?w conll:REF_EXP "pron"; conll:REF "?OLD"
} WHERE {
	?w conll:UPOS "PRON".
	MINUS { ?w conll:REF [] }
};

INSERT {
	?w conll:REF_EXP "ne"; conll:REF "?OLD"
} WHERE {
	?w conll:UPOS "PROPN".
	MINUS { ?w conll:EDGE "compound" }
	MINUS { ?w conll:EDGE "flat" }
	MINUS { ?w conll:REF [] }
};

INSERT {
	?w conll:REF_EXP "def-np.dem"; conll:REF "?OLD"
} WHERE {
	?def conll:FEATS ?f; conll:EDGE "det"; conll:HEAD ?w.
	FILTER(contains(?f,"PronType=Dem"))
	?w conll:UPOS "NOUN"
	MINUS { ?w conll:REF [] }
};

INSERT {
	?w conll:REF_EXP "def-np.poss"; conll:REF "?OLD"
} WHERE {
	?def conll:EDGE "nmod:poss"; conll:HEAD ?w.
	?w conll:UPOS "NOUN"
	MINUS { ?w conll:REF [] }
};

INSERT {
	?w conll:REF_EXP "def-np.poss"; conll:REF "?OLD"
} WHERE {
	?def conll:EDGE "nmod"; conll:HEAD ?w.
	?w conll:UPOS "NOUN"
	MINUS { ?w conll:REF [] }
};

INSERT {
	?w conll:REF_EXP "def-np.poss"; conll:REF "?OLD"
} WHERE {
	?def conll:EDGE "det"; conll:FEATS ?f; conll:HEAD ?w.
	?w conll:UPOS "NOUN".
	FILTER(contains(?f,"PronType=Poss"))
	MINUS { ?w conll:REF [] }
};


INSERT {
	?w conll:REF_EXP "def-np.the"; conll:REF "?OLD"
} WHERE {
	?def conll:LEMMA ?lemma; conll:EDGE "det"; conll:HEAD ?w.
	FILTER(?lemma in ("la", "lo", "il", "le", "gli", "i"))
	?w conll:UPOS "NOUN"
	MINUS { ?w conll:REF [] }
};

# quant-NP: this is for numeral NPs with definite determiner
INSERT {
	?w conll:REF_EXP "def-np.quant"; conll:REF "?OLD"
} WHERE {
	?def conll:EDGE "det"; conll:FEATS ?f; conll:HEAD ?w.
	FILTER(contains(?f,"Definite=Def"))
	?card conll:UPOS "NUM"; conll:HEAD ?w. 
	?w conll:UPOS "NOUN"
	MINUS { ?w conll:REF [] }
};

# the-np
INSERT {
	?w conll:REF_EXP "def-np.the"; conll:REF "?OLD"
} WHERE {
	?def conll:EDGE "det"; conll:FEATS ?f; conll:HEAD ?w.
	FILTER(contains(?f,"Definite=Def"))
	?w conll:UPOS "NOUN"
	MINUS { ?w conll:REF [] }
};

# def. nps in general
INSERT {
	?w conll:REF_EXP "def-np"; conll:REF "?OLD"
} WHERE {
	?def conll:FEATS ?f; conll:EDGE "det"; conll:HEAD ?w.
	FILTER(contains(?f,"Definite=Def"))
	?w conll:UPOS "NOUN"
	MINUS { ?w conll:REF [] }
};

# other-NP: any def-np that contains "other" => .other suffix
# not separated

# indef-np.a
INSERT {
	?w conll:REF_EXP "indef-np.a"; conll:REF "?NEW"
} WHERE {
	?det conll:EDGE "det"; conll:FEATS ?f; conll:HEAD ?w.
	FILTER(contains(?f,"Definite=Ind"))
	FILTER(contains(?f,"PronType=Art"))
	?w conll:UPOS "NOUN".
	MINUS { ?w conll:REF [] }
};

# indef-np.quant
INSERT {
	?w conll:REF_EXP "indef-np.quant"; conll:REF "?NEW"
} WHERE {
	{ ?quant conll:UPOS "NUM" } UNION
	{ ?quant conll:FEATS ?f FILTER(contains(?f,"PronType=Tot")) } UNION
	{ ?quant conll:FEATS ?f FILTER(contains(?f,"PronType=Neg")) }
	?quant conll:HEAD ?w.
	?w conll:UPOS "NOUN".
	MINUS { ?w conll:REF [] }
};

# indef-np.bare: no determiner
INSERT {
	?w conll:REF_EXP "indef-np.bare"; conll:REF "?NEW"
} WHERE {
	?w conll:UPOS "NOUN".
	MINUS { ?w conll:REF [] }
	MINUS { [ conll:UPOS "DET" ] conll:HEAD ?w }
};

# indef-np: generic indefinite np
INSERT {
	?w conll:REF_EXP "indef-np"; conll:REF "?NEW"
} WHERE {
	?w conll:UPOS "NOUN".
	MINUS { ?w conll:REF [] }
};

# other
INSERT {
	?w conll:REF_EXP "other"; conll:REF "?NEW"
} WHERE {
	?w conll:EDGE ?e.
	FILTER(regex(?e,":.*","") in ("nmod", "nsubj", "obj", "dobj", "iobj", "obl"))
	MINUS { ?w conll:REF [] }
};

##################
# postprocessing #
##################

# remove `?NEW` and `BOUND`
# note: this is to facilitate spreadsheet-based annotation, so people can use <CTRL>+<DOWN> to jump to the next primary markable
#       for doing the same for secondary markables, annotators should use the `REF_EXP` column. 

DELETE {
	?w conll:REF "?NEW"
} WHERE {
	?w conll:REF "?NEW"
};

DELETE {
	?w conll:REF "BOUND"
} WHERE {
	?w conll:REF "BOUND"
};

# rename REF_EXP to NP_TYPE (for consistency with Chiarcos and Krasavina 2005)
DELETE {
	?w conll:REF_EXP ?re
} INSERT {
	?w conll:NP_TYPE ?re
} WHERE {
	?w conll:REF_EXP ?re
	};