PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#> 
PREFIX nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> 
PREFIX powla: <http://purl.org/powla/powla.owl#> 
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX terms: <http://purl.org/acoli/open-ie/> 
PREFIX x:     <http://purl.org/acoli/conll-rdf/xml#> 
PREFIX apf:   <http://jena.apache.org/ARQ/property#>

# split attribute values, if they contain '|'
DELETE {
	?w ?prop ?feat
} INSERT {
	?w ?prop ?part
} WHERE {
	?w a nif:Word; ?prop ?feat.
	FILTER(contains(?feat,"|"))
	?part apf:strSplit(?feat "[|]")
};

# remove conll:coref_coref_class from punctuations
DELETE {
	?w conll:coref_coref_class ?coref_coref_class
} WHERE {
	?w conll:coref_coref_class ?coref_coref_class.
	?w conll:UPOS ?upos
	FILTER(?upos in ("SYM","PUNCT"))
};

# head reduction
# drop conll:coref_coref_class if the head has the same
DELETE {
	?w conll:coref_coref_class ?coref_coref_class
} WHERE {
	?w conll:coref_coref_class ?coref_coref_class.
	?w conll:HEAD/conll:coref_coref_class ?coref_coref_class.
};

# post-filtering
# drop "empty" (these are expletives)
DELETE {
	?w conll:coref_coref_class ?value
} WHERE {
	?w conll:coref_coref_class ?value
	FILTER(?value in ("empty"))
};

# feature simplification: if more than one feature applies to the same word, pick the lexicographically first
DELETE {
	?w ?prop ?val2
} WHERE {
	?w a nif:Word; ?prop ?val1, ?val2.
	FILTER(isliteral(?val1))
	FILTER(isliteral(?val2))
	FILTER(?val1 != ?val2)
	FILTER(?val1 < ?val2)
};